# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-04 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0006_auto_20161024_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='photo',
            field=models.FileField(blank=True, upload_to='gigs'),
        ),
    ]
